NUKURI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, LogoutView,PasswordChangeView, PasswordChangeDoneView
)

import authentification.views
from iga.views import (
    PhotoAPIView, BlogAPIView, BlogContributorAPIView,
    FollowUsersView, ViewBlogView, EditBlogView,
    PhotoUploadView, CreateMultiplePhotosView, HomeView, BlogAndPhotoUploadView, CommentView
)

from rest_framework.routers import DefaultRouter
from iga.views import PhotoViewSet, BlogViewSet, BlogContributorViewSet


router = DefaultRouter()
router.register('photos', PhotoViewSet, basename='photo')
router.register('blogs', BlogViewSet, basename='blog')
router.register('blog-contributors', BlogContributorViewSet, basename='blogcontributor')


urlpatterns = [
    path('admin/', admin.site.urls),
   path('home', LoginView.as_view(
           template_name='authentication/login.html',
           redirect_authenticated_user=True),
        name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html'),
         name='password_change'
         ),
    path('change-password-done/', PasswordChangeDoneView.as_view(
        template_name='authentication/password_change_done.html'),
         name='password_change_done'
         ),
    path('home/', HomeView.as_view(), name='home'),
    path('signup/', authentification.views.signup_page, name='signup'),
    path('photo/upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('profile-photo/upload/', authentification.views.upload_profile_photo,
         name='upload_profile_photo'),
    path('iga/create', BlogAndPhotoUploadView.as_view(), name='blog_create'),
    path('iga/<int:blog_id>', ViewBlogView.as_view, name='view_blog'),
    path('iga/<int:blog_id>/edit', EditBlogView.as_view(), name='edit_blog'),
    path('photo/upload-multiple/', CreateMultiplePhotosView.as_view(), name='create_multiple_photos'),
    path('follow-users/', FollowUsersView.as_view(), name='follow_users'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api/photo/', PhotoAPIView.as_view(), name='photo_api'),
    path('api/blog/', BlogAPIView.as_view(), name='blog_api'),
    path('api/blogcontributor/', BlogContributorAPIView.as_view(), name='blog_contributor_api'),
    path('iga/', include('iga.urls')),
    path('leave/', include('leave.urls')),
    path('', authentification.views.index, name='index'),
    path('comments/', CommentView.as_view(), name='comments'),
  
    

   


]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iga/urls.py
from django.urls import path
from . import views
from .views import EditPhotoView

urlpatterns = [
    path('index/', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
     path('privacy_and_policy/', views.privacy_and_policy, name='privacy_and_policy'),
     path('edit/<int:photo_id>', EditPhotoView.as_view(), name='edit_photo'),
     
]

iga/models.py
from django.conf import settings
from django.db import models
from PIL import Image
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from authentification.models import User

class Post(models.Model):
    title= models.CharField(max_length=200)
    content= models.CharField()
    pub_date = models.DateTimeField('date published')

class Photo(models.Model):
    IMAGE_MAX_SIZE = (800, 800)

    image = models.ImageField()
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        # save the resized image to the file system
        # this is not the model save method!
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributed_blogs')
    
    language = models.CharField(
         max_length=50,
         choices=[
              ('en', _('English')),
              ('fr', _('French')),
              ('ki', _('kirundi')),
         ],
        default='English')
    created_at = models.DateTimeField(default=timezone.now)
    

    def _get_word_count(self):
        return len(self.content.split(' '))

    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)
        exit

    class Meta:
        permissions = [
            ('change_blog_title', 'Can change the title of a blog')
        ]
class BlogContributor(models.Model):
            contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
            blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
            contribution = models.CharField(max_length=255, blank=True)
            
            class Meta:
                 unique_together = ('contributor', 'blog')

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.timestamp}'
    
    def user_can_delete(self, user):
        return user == self.user

iga/forms.py
from django import forms
from django.contrib.auth import get_user_model
from . import models

class PhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ['image', 'caption']

class BlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'content']
class DeleteBlogForm(forms.Form):
    delete_blog = forms.BooleanField(widget=forms.HiddenInput, initial=True)

class DeletePhotoForm(forms.Form):
    delete_photo = forms.BooleanField(widget=forms.HiddenInput, initial=True)
User = get_user_model()


class FollowUsersForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['follows']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['text']

iga/views.py
from itertools import chain
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.forms import formset_factory
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from .models import Blog,Comment
from .forms import CommentForm




from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from iga.models import Photo, Blog, BlogContributor
from iga.serializers import PhotoSerializer, BlogSerializer, BlogContributorSerializer
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from iga.forms import PhotoForm, BlogForm, DeleteBlogForm, FollowUsersForm, DeletePhotoForm




from . import forms, models


class PhotoAPIView(APIView):
    def get(self, *args, **kwargs):
        photos = Photo.objects.all()
        serializer = PhotoSerializer(photos, many=True)
        return Response(serializer.data)


class BlogAPIView(APIView):
    def get(self, *args, **kwargs):
        blogs = Blog.objects.all()
        serializer = BlogSerializer(blogs, many=True)
        return Response(serializer.data)


class BlogContributorAPIView(APIView):
    def get(self, *args, **kwargs):
        contributors = BlogContributor.objects.all()
        serializer = BlogContributorSerializer(contributors, many=True)
        return Response(serializer.data)
   


class PhotoViewSet(ReadOnlyModelViewSet):
   
    serializer_class = PhotoSerializer


    def get_queryset(self):
        return models.Photo.objects.filter(active=True)


class BlogViewSet(ReadOnlyModelViewSet):
   
    serializer_class = BlogSerializer


    def get_queryset(self):
        queryset = Blog.objects.filter(active=True)
        photo_id = self.request.GET.get('photo_id')
        if photo_id is not None:
            queryset = queryset. filter(photo_id=photo_id)
            return queryset


class BlogContributorViewSet(ReadOnlyModelViewSet):
   
    serializer_class = BlogContributorSerializer


    def get_queryset(self):
        return BlogContributor.objects.filter(active=True)








class PhotoUploadView(LoginRequiredMixin, View):
    template_name = 'iga/photo_upload.html'


    def get(self, request, *args, **kwargs):
        form = PhotoForm()
        return render(request, self.template_name, context={'form': form})


    def post(self, request, *args, **kwargs):
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            return redirect('home')
        return render(request, self.template_name, context={'form': form})
   
class HomeView(LoginRequiredMixin, View):
    template_name = 'iga/home.html'
    paginate_by = 6
    context_object_name = 'blog_posts'

    def get(self, request, *args, **kwargs):
        # If not logged in, redirect or handle unauthenticated users as needed
        if not request.user.is_authenticated:
            return render(request, 'iga/index.html')

        # Retrieve all blogs and photos without user-specific filters
        blogs = Blog.objects.all()
        photos = Photo.objects.all()

        # Combine blogs and photos and order by date_created
        blogs_and_photos = sorted(
            chain(blogs, photos),
            key=lambda instance: instance.date_created,
            reverse=True
        )

        # Paginate the result
        paginator = Paginator(blogs_and_photos, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'page_obj': page_obj, 'blogs': blogs}
        return render(request, self.template_name, context=context)


   
class BlogAndPhotoUploadView(LoginRequiredMixin, View):
    template_name = 'iga/create_blog_post.html'


    def get(self, request, *args, **kwargs):
        blog_form = BlogForm()
        photo_form = PhotoForm()
        context = {
            'blog_form': blog_form,
            'photo_form': photo_form,
        }
        return render(request, self.template_name, context=context)


    def post(self, request, *args, **kwargs):
        blog_form = BlogForm(request.POST)
        photo_form = PhotoForm(request.POST, request.FILES)
        if all([blog_form.is_valid(), photo_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            blog = blog_form.save(commit=False)
            blog.photo = photo
            blog.save()
            blog.contributors.add(request.user, through_defaults={'contribution': 'Primary Author'})
            return redirect('home')
        else:
            context = {
                'blog_form': blog_form,
                'photo_form': photo_form,
            }
            return render(request, self.template_name, context=context)







class ViewBlogView(LoginRequiredMixin, View):
    template_name = 'iga/view_blog.html'


    def get(self, request, blog_id, *args, **kwargs):
        blog = get_object_or_404(Blog, id=blog_id)
        return render(request, self.template_name, {'blog': blog})




class EditBlogView(LoginRequiredMixin, View):
    template_name = 'iga/edit_blog.html'


    def get(self, request, blog_id, *args, **kwargs):
        blog = get_object_or_404(Blog, id=blog_id)
        edit_form = BlogForm(instance=blog)
        delete_form = DeleteBlogForm()
        context = {
            'edit_form': edit_form,
            'delete_form': delete_form,
        }
        return render(request, self.template_name, context=context)


    def post(self, request, blog_id, *args, **kwargs):
        blog = get_object_or_404(Blog, id=blog_id)
        edit_form = BlogForm(request.POST, instance=blog)
        delete_form = DeleteBlogForm(request.POST)
        if 'edit_blog' in request.POST:
            if edit_form.is_valid():
                edit_form.save()
                return redirect('home')
        elif 'delete_blog' in request.POST:
            if delete_form.is_valid():
                blog.delete()
                return redirect('home')


        context = {
            'edit_form': edit_form,
            'delete_form': delete_form,
        }
        return render(request, self.template_name, context=context)

class EditPhotoView(LoginRequiredMixin, View):
    template_name = 'iga/edit_photo.html'

    def get(self, request, photo_id, *args, **kwargs):
        photo = get_object_or_404(Photo, id=photo_id)
        edit_form = PhotoForm(instance=photo)
        delete_form = DeletePhotoForm()

        context = {
            'photo': photo,
            'edit_form': edit_form,
            'delete_form': delete_form,
        }

        return render(request, self.template_name, context=context)

    def post(self, request, photo_id, *args, **kwargs):
        photo = get_object_or_404(Photo, id=photo_id)
        edit_form = PhotoForm(request.POST, instance=photo)
        delete_form = DeletePhotoForm(request.POST)

        if 'edit_photo' in request.POST:
            if edit_form.is_valid():
                edit_form.save()
                return redirect('home')
        elif 'delete_photo' in request.POST:
            if delete_form.is_valid():
                photo.delete()
                return redirect('home')

        context = {
            'photo': photo,
            'edit_form': edit_form,
            'delete_form': delete_form,
        }

        return render(request, self.template_name, context=context)
    

class CreateMultiplePhotosView(LoginRequiredMixin, View):
    template_name = 'iga/create_multiple_photos.html'
    formset_class = formset_factory(PhotoForm, extra=5)


    def get(self, request, *args, **kwargs):
        formset = self.formset_class()
        context = {'formset': formset}
        return render(request, self.template_name, context=context)


    def post(self, request, *args, **kwargs):
        formset = self.formset_class(request.POST, request.FILES)
        if formset.is_valid():
            for form in formset:
                if form.cleaned_data:
                    photo = form.save(commit=False)
                    photo.uploader = request.user
                    photo.save()
            return redirect('home')
        context = {'formset': formset}
        return render(request, self.template_name, context=context)
   
class FollowUsersView(LoginRequiredMixin, View):
    template_name = 'iga/follow_users_form.html'

    def get(self, request, *args, **kwargs):
        form = FollowUsersForm(instance=request.user)
        context = {'form': form}
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = FollowUsersForm(request.POST, instance=request.user)
        if form.is_valid():
            followed_user = form.save()

            # Add a success message
            messages.success(
                request,
                f"You are now following {followed_user.username}."
            )

            return redirect('home')

        # If form is not valid, render the form again with errors
        context = {'form': form}
        return render(request, self.template_name, context=context)
class PasswordChangeView(LoginRequiredMixin, View):
    template_name = 'password_change_form.html'
    success_message = "Your password was changed successfully."
    success_url = reverse_lazy('password_change_done')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response

class PasswordChangeDoneView(LoginRequiredMixin, View):
    template_name = 'password_change_done.html'

iga/templates/iga/about-us.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link rel="stylesheet" href="{% static 'css/aboutus.css' %}">
</head>

<body>

    <header>
        <div id="top-left-buttons">
            <a href="{% url 'signup' %}" id="signup-btn">Sign Up</a>
            <span id="slash">/</span>
            <a href="{% url 'login' %}" id="signin-btn">Sign in</a>
        </div>
        <div class="header-content">
            <nav>
                <ul>
                    <li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                    <li><a href="{% url 'about_us' %}" class="nav-link">About Us</a></li>
                    <li><a href="{% url 'contact_us' %}" class="nav-link">Contact Us</a></li>
                    <li><a href="{% url 'privacy_and_policy' %}" class="nav-link">Privacy and Policy</a></li>
                </ul>
            </nav>
        
        </div>
    </header>
    <section class="about-us">
        <h1>About IGA</h1>
        <p>IGA came to our minds when we realized how many girls and women are deprived of education due to poverty, culture, gender bias, and other factors. We thought that some women who have overcome these challenges and achieved success in life could support those who are less fortunate, by sharing some of their resources and knowledge, either online or in person, and by telling their stories on IGA. That's how we created IGA.</p>
        <p>IGA is a website that aims to leverage technology to provide quality and accessible education to women, thus bridging the gender gap in education.</p>

    <p>The meaning of IGA in English is "STUDY or LEARN". It is a Kirundi word and the name of this website that lets users share blogs or photos related to education. Only educational content is allowed on this website. We want users who post on this website to tell us how online education has helped them or not. We also want them to include links to the courses they have taken on their blogs and to show us photos of their transformation after taking these courses (before and after). This is to inspire young people who visit this website, especially girls and Women who have lost hope.</p>

    </section>
{% endblock %}



    

iga/templates/iga/contact_us.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <link rel="stylesheet" href="{% static 'css/contact_us.css' %}">
</head>

<body>

    <header>
        <div id="top-left-buttons">
            <a href="{% url 'signup' %}" id="signup-btn">Sign Up</a>
            <span id="slash">/</span>
            <a href="{% url 'login' %}" id="signin-btn">Sign in</a>
        </div>
        <div class="header-content">
            <nav>
                <ul>
                    <li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                    <li><a href="{% url 'about_us' %}" class="nav-link">About Us</a></li>
                    <li><a href="{% url 'contact_us' %}" class="nav-link">Contact Us</a></li>
                    <li><a href="{% url 'privacy_and_policy' %}" class="nav-link">Privacy and Policy</a></li>
                </ul>
            </nav>
            
        </div>
    </header>


<section class="contact_us">
    <h2>Contact Us</h2>
    <p>Phone number: +25766306494</p>
    <p>Email: ardinemartinenukuri@gmail.com</p>
    <p>If you have any questions or inquiries, feel free to reach out to us:</p>
      <form>
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <label for="message">Message:</label>
        <textarea id="message" name="message" required></textarea>
        <button type="submit">Send</button>
      </form>
</section>

{% endblock %}

iga/templates/iga/create_blog_post.html
{% extends 'base.html' %}
{% block content %}
    <h2>Create a Post</h2>
    <form method="post" enctype="multipart/form-data">
        {{ blog_form.as_p }}
        {{ photo_form.as_p }}
        {% csrf_token %}
        <button type="submit" >Submit</button>
    </form>
    {% for photo in blog.photos.all %}
    <img src="{{ photo.image.url }}" alt="Photo">
{% endfor %}
{% endblock content %}

iga/templates/iga/create_multiple_photos.html
{% extends 'base.html' %}
{% block content %}
   <h2>Add Photos</h2>
   <form method="post" enctype="multipart/form-data">
       {{ formset.managment_form }}
       {% csrf_token %}
       {% for form in formset %}
           {{ form.as_p }}
       {% endfor %}
       <button type="submit" >Post </button>
   </form>
{% endblock content %}

iga/templates/iga/delete_blog.html
{% extends 'base.html' %}
{% block content %}
<h3>Delete Blog?  {{ blog.title }}</h3>
    <form method="post">
        {{ delete_form }}
        {% csrf_token %}
        <button type="submit" >Delete</button>
    </form>
    
    {% endblock %}

iga/templates/iga/edit_blog.html
{% extends 'base.html' %}
{% block content %}
    <h2>Edit Blog</h2>
    <form method="post">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <button type="submit" >Save</button>
    </form>
    <hr>
    <h3>Delete Blog?  {{ blog.title }}</h3>
    <form method="post">
        {{ delete_form }}
        {% csrf_token %}
        <button type="submit" >Delete</button>
    </form>
    
    {% endblock %}

    

iga/templates/iga/edit_photo.html
{% extends 'base.html' %}
{% block content %}

<h4>Delete Photo?  {{ photo.title }}</h4>
    <form method="post">
        {{ delete_form }}
        {% csrf_token %}
        <button type="submit" >Delete</button>
    </form>
{% endblock content %}

iga/templates/iga/follow_users_form.html
{% extends 'base.html' %}
{% block content %}
    <h2>Follow Users</h2>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" >Confirm</button>
    </form>

   

  <h3>Available Users</h3>
  {% for user in users %}
  <ol><li>{{ user.username }}</li></ol>
  <ul>
    
      
        
        <li>{{ user.email }}</li>
        <li>{{ user.role }}</li>
    
        <input type="checkbox" name="users_to_follow" value="{{ user.id }}">
      
    {% endfor %}
  </ul>

{% endblock content %}

iga/templates/iga/home.html
{% extends 'base.html' %}
{% load blog_extras %}
{% block content %}
    <h2>Your Feed</h2>
    <div class="grid-container">
        {% for instance in page_obj %}
            {% if instance|model_type == 'Blog' %}
                {% include 'iga/partials/blog_snippet.html' with blog=instance %}
            {% elif instance|model_type == 'Photo' %}
                {% include 'iga/partials/photo_snippet.html' with photo=instance %}
            {% elif instance|model_type == 'Photo' %}
                {% include 'photo_upload.html' with photo=instance %}
            {% endif %}
        {% endfor %}
    </div>
    {% include 'partials/page_navigator.html' %}
{% endblock content %}

iga/templates/iga/index.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Frontend</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

    <header>
        <div id="top-left-buttons">
            <a href="{% url 'signup' %}" id="signup-btn">Sign Up</a>
            <span id="slash">/</span>
            <a href="{% url 'login' %}" id="signin-btn">Sign in</a>
        </div>
        <div class="header-content">
            <nav>
                <ul>
                    <li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                    <li><a href="{% url 'about_us' %}" class="nav-link">About Us</a></li>
                    <li><a href="{% url 'contact_us' %}" class="nav-link">Contact Us</a></li>
                    <li><a href="{% url 'privacy_and_policy' %}" class="nav-link">Privacy and Policy</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="main-content">
      <main>
      <p><strong>Welcome to IGA</strong></p> 
      <img src="{% static 'img/women_in-education.png' %}" alt="Women in Education">
      <h1>“Education is the passport to the future, for tomorrow belongs to those who prepare for it today.” – Malcolm X</h1> 
    
      </main>
  </div>


  
</body>

</html>
{% endblock %}

iga/templates/iga/photo_upload.html
{% extends 'base.html' %}
{% block content %}
    <h2>Upload a Photo</h2>
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" >Submit</button>
    </form>
    <p>Not a member? <a href="{% url 'signup' %}">Sign up now!</a></p>
{% endblock content %}

iga/templates/iga/post_confirm_delete.html
{% extends base.html %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ blog.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

iga/templates/iga/privacy_and_policy.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>privacy_and_policy</title>
    <link rel="stylesheet" href="{% static 'css/privacy.css' %}">
</head>

<body>

    <header>
        <div id="top-left-buttons">
            <a href="{% url 'signup' %}" id="signup-btn">Sign Up</a>
            <span id="slash">/</span>
            <a href="{% url 'login' %}" id="signin-btn">Sign in</a>
        </div>
        <div class="header-content">
            <nav>
                <ul>
                    <li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                    <li><a href="{% url 'about_us' %}" class="nav-link">About Us</a></li>
                    <li><a href="{% url 'contact_us' %}" class="nav-link">Contact Us</a></li>
                    <li><a href="{% url 'privacy_and_policy' %}" class="nav-link">Privacy and Policy</a></li>
                </ul>
            </nav>
        
              
            </form>
        </div>
    </header>



<body>
    <section class="privacy_and_policy">
    <h1>Privacy Policy for IGA</h1>

    <p>Effective Date: November,8,2023</p>

    <h2>1. Introduction</h2>

    <p>Welcome to IGA . At IGA, we respect your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website and services.</p>

    <p>By accessing or using our website, you consent to the practices described in this Privacy Policy. Please take a moment to review this policy and let us know if you have any questions.</p>

    <h2>2. Information We Collect</h2>

    <ul>
        <li><strong>Personal Information:</strong> When you interact with our website, we may collect personal information such as your name, email address, contact information, and any other information you provide voluntarily.</li>

        <li><strong>Automatically Collected Information:</strong> We may also automatically collect certain information about your device and usage patterns, including your IP address, browser type, operating system, and other technical details.</li>
    </ul>

    <h2>3. How We Use Your Information</h2>

    <p>We use the information we collect for various purposes, including:</p>

    <ul>
        <li>Providing and improving our services</li>
        <li>Personalizing your experience</li>
        <li>Responding to your inquiries and requests</li>
        <li>Sending you updates, newsletters, and promotional materials</li>
        <li>Conducting research and analysis</li>
        <li>Ensuring the security and integrity of our website</li>
    </ul>



    <h2>10. Contact Us</h2>

    <p>If you have any questions, concerns, or requests regarding this Privacy Policy, please contact us at:</p>

    <p>Phone number: +25766306494

        Email: ardinemartinenukuri@gmail.com</p>

</body>

</html>

{% endblock %}

iga/templates/iga/view_blog.html
{% block content %}
   <h2>{{ blog.title }}</h2>
   <p><a href="{% url 'edit_blog' blog.id %}">Edit Blog</a></p>
   {% if perms.blog.change_blog %}
   <img src="{{ iga.photo.image.url }}">
   <p>{{ blog.photo.caption }}</p>
   <p>{{ blog.content }}</p>
{% endblock content %}